// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kiefvllciludhnvjwzbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpZWZ2bGxjaWx1ZGhudmp3emJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0MTAzMDksImV4cCI6MjA3OTk4NjMwOX0.91uIpY5_UnwUtpIR-inrh1fd9iuyV3c7qBsWvQ4LB0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});